version: '3'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes: 
      - ./data/db:/data/db
    ports:
      - 27017:27017

  web:
    build: .
    container_name: node-web
    restart: always
    volumes:
      - ./www/api:/var/www/api
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mongo:27017

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - web